---
apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
spec:
  volumes:
    - name: log-files
      emptyDir: {}
  containers:
  - name: web-server
    image: nginx
    volumeMounts:
    - name: log-files
      mountPath: /var/log/nginx
  - name: web-logger
    image: busybox:latest
    command: ["/bin/sh", "-c", "while true; do cat /var/log/nginx/access.log; sleep 30; done"]
    volumeMounts:
    - name: log-files
      mountPath: /var/log/nginx