apiVersion: v1
kind: Pod
metadata:
  name: pod2
spec:
  volumes:
    - name: vol2
      persistentVolumeClaim:
       claimName: pvc2
  containers:
   - name: busybox-container
     image: busybox:1.30.1
     command: ['sh', '-c', 'while true; do date; sleep 3; done']
     volumeMounts:
       - mountPath: "/dynamic-vol"
         name: vol2