apiVersion: v1
kind: Pod
metadata:
  name: busyboxed-pod
  annotations:
    creator: icingcode
    environment: test
spec:
  volumes:
    - name: busyboxed-volume
      emptyDir:
        sizeLimit: 500Mi
  containers:
    - name: busyboxed-container
      image: busybox:latest
      command: ['sh', '-c', 'while true; do echo "Hello world"; sleep 10; done']
      volumeMounts:
      - mountPath: /busyboxed-data
        name: busyboxed-volume

#kubectl exec busyboxed-pod -c busyboxed-container -it -- sh