apiVersion: v1
kind: Pod
metadata:
  name: pod1
spec:
  containers:
  - name: busybox-container
    image: busybox:latest
    command: ['sh', '-c', 'while true; do date; sleep 3; done']
    volumeMounts:
    - mountPath: /projects
      name: projects-vol
  volumes:
  - name: projects-vol
    nfs:
      server: 192.168.1.10
      path: /mounts/nfs/data