apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-storage
provisioner: kubernetes.io/no-provisioner
parameters:
  server: 192.168.1.10
  path: /mounts/nfs/data
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer